// <auto-generated />
using System;
using Echo.API.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Echo.API.Database.Migrations
{
    [DbContext(typeof(EchoDbContext))]
    [Migration("20260605022109_ChangeTranscriptionJobRelationship")]
    partial class ChangeTranscriptionJobRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Echo.API.Entities.Recording", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("S3Key")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("s3_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("TranscribedText")
                        .HasColumnType("TEXT")
                        .HasColumnName("transcribed_text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_recordings");

                    b.ToTable("recordings", (string)null);
                });

            modelBuilder.Entity("Echo.API.Entities.TranscriptionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("failure_reason");

                    b.Property<Guid>("RecordingId")
                        .HasColumnType("TEXT")
                        .HasColumnName("recording_id");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("retry_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_transcription_jobs");

                    b.HasIndex("RecordingId")
                        .IsUnique()
                        .HasDatabaseName("ix_transcription_jobs_recording_id");

                    b.ToTable("transcription_jobs", (string)null);
                });

            modelBuilder.Entity("Echo.API.Entities.TranscriptionJob", b =>
                {
                    b.HasOne("Echo.API.Entities.Recording", "Recording")
                        .WithOne("TranscriptionJob")
                        .HasForeignKey("Echo.API.Entities.TranscriptionJob", "RecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transcription_jobs_recordings_recording_id");

                    b.Navigation("Recording");
                });

            modelBuilder.Entity("Echo.API.Entities.Recording", b =>
                {
                    b.Navigation("TranscriptionJob")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
