services:
  api:
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ./src/backend:/app/src/backend

  postgres:
    ports:
      - "5432:5432"

  minio:
    ports:
      - "9000:9000"
      - "9001:9001"
