services:
  api:
    image: ${ECHO_API_IMAGE:-gustmrg/echo-api:latest}
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production

  worker:
    image: ${ECHO_WORKER_IMAGE:-gustmrg/echo-worker:latest}
    restart: unless-stopped

  minio:
    restart: unless-stopped
